name: PHP Coding Standards

on:
    workflow_call:
        inputs:
            php-version:
                description: 'The PHP version to use when running the job'
                default: '8.3'
                required: false
                type: 'string'

jobs:
    php-codesniffer:
        name: PHP_CodeSniffer
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version:
                    - '${{ inputs.php-version }}'

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '${{ matrix.php-version }}'
                    tools: cs2pr

            -   name: Install dependencies with Composer
                uses: ramsey/composer-install@v3

            -   name: Run PHP_CS
                run: vendor/bin/phpcs --no-colors --report=checkstyle -q | cs2pr --graceful-warnings
